title: "明日葉の自由帳"
plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge

collections:
  experiments:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: experiment
