title: "明日葉の自由帳"
author: "明日葉"
markdown: kramdown
highlighter: rouge

collections:
  experiments:
    output: true
  issues:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: post
  - scope:
      path: ""
      type: "issues"
    values:
      layout: issue
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
